apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      hostNetwork: true
      containers:
      - name: client-container
        imagePullPolicy: Always
        image: alexsaavedraa/client:v2 # Replace with your actual image name and tag


