apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  selector:
    app: client
  ports:
  - protocol: TCP
    port: 8081  # Port exposed externally
    targetPort: 1234  # Port exposed by the client container
