version: '3'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8080:1234"

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "8081:1234"
