apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server-container
        image: alexsaavedraa/nimble_challenge-server  # Replace with your actual image name and tag
        ports:

        - containerPort: 1234  # Port exposed by the server container
---
apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  selector:
    app: server
  ports:
  - protocol: TCP
    port: 8080  # Port exposed externally
    targetPort: 1234  # Port exposed by the server container

