apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  selector:
    app: server
  ports:
  - protocol: TCP
    port: 8080  # Port exposed externally
    targetPort: 1234  # Port exposed by the server container
